"""init_db

Revision ID: 379afadafdd7
Revises: 8f2c8b9a3c2b
Create Date: 2025-11-04 03:04:47.629468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '379afadafdd7'
down_revision: Union[str, Sequence[str], None] = '8f2c8b9a3c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_items')
    op.drop_table('servers')
    op.drop_table('items')
    op.alter_column('achievements', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'achievements', ['name'])
    op.add_column('admin_requests', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('admin_requests', 'telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('admins', 'telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.add_column('promocodes', sa.Column('reward', sa.Integer(), nullable=True))
    op.add_column('promocodes', sa.Column('reward_type', sa.String(), nullable=True))
    op.add_column('promocodes', sa.Column('uses_left', sa.Integer(), nullable=True))
    op.drop_column('promocodes', 'promo_type')
    op.drop_column('promocodes', 'uses')
    op.drop_column('promocodes', 'max_uses')
    op.drop_column('promocodes', 'active')
    op.drop_column('promocodes', 'value')
    op.add_column('topup_requests', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('topup_requests', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_column('topup_requests', 'currency')
    op.add_column('user_achievements', sa.Column('earned_at', sa.DateTime(), nullable=True))
    op.alter_column('user_achievements', 'tg_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_foreign_key(None, 'user_achievements', 'achievements', ['achievement_id'], ['id'])
    op.drop_column('users', 'play_time')
    op.drop_column('users', 'referrals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrals', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('play_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_achievements', type_='foreignkey')
    op.alter_column('user_achievements', 'tg_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('user_achievements', 'earned_at')
    op.add_column('topup_requests', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('topup_requests', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('topup_requests', 'created_at')
    op.add_column('promocodes', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('promocodes', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('promocodes', sa.Column('max_uses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('promocodes', sa.Column('uses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('promocodes', sa.Column('promo_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('promocodes', 'uses_left')
    op.drop_column('promocodes', 'reward_type')
    op.drop_column('promocodes', 'reward')
    op.alter_column('admins', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('admin_requests', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('admin_requests', 'created_at')
    op.drop_constraint(None, 'achievements', type_='unique')
    op.alter_column('achievements', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey')),
    sa.UniqueConstraint('name', name=op.f('items_name_key'))
    )
    op.create_table('servers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('closed_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('servers_pkey')),
    sa.UniqueConstraint('number', name=op.f('servers_number_key'))
    )
    op.create_table('shop_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('item_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('shop_items_pkey'))
    )
    # ### end Alembic commands ###
